spring.application.name=ecom-demo

# Read the string from Replit Secrets, fallback to local host if missing
# spring.datasource.url={DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Neon provides the user/password right inside the URI string, 
# but if your string splits them up, you can map them like this:
# spring.datasource.username=${DB_USERNAME:postgres}
# spring.datasource.password=${DB_PASSWORD:password}